name: Build binary

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Build
      run: dotnet publish -r linux-x64 --self-contained -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:StripSymbols=true -c Release -o publish src/Gamerun/Gamerun.csproj
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        path: src/Gamerun/publish/gamerun
      
